# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wordcount.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'wordcount.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwordcount.proto\x12\twordcount\"&\n\x10WordCountRequest\x12\x12\n\ntext_chunk\x18\x01 \x01(\t\"v\n\x0eWordCountReply\x12\x35\n\x06\x63ounts\x18\x01 \x03(\x0b\x32%.wordcount.WordCountReply.CountsEntry\x1a-\n\x0b\x43ountsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x32S\n\tWordCount\x12\x46\n\nCountWords\x12\x1b.wordcount.WordCountRequest\x1a\x19.wordcount.WordCountReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wordcount_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORDCOUNTREPLY_COUNTSENTRY']._loaded_options = None
  _globals['_WORDCOUNTREPLY_COUNTSENTRY']._serialized_options = b'8\001'
  _globals['_WORDCOUNTREQUEST']._serialized_start=30
  _globals['_WORDCOUNTREQUEST']._serialized_end=68
  _globals['_WORDCOUNTREPLY']._serialized_start=70
  _globals['_WORDCOUNTREPLY']._serialized_end=188
  _globals['_WORDCOUNTREPLY_COUNTSENTRY']._serialized_start=143
  _globals['_WORDCOUNTREPLY_COUNTSENTRY']._serialized_end=188
  _globals['_WORDCOUNT']._serialized_start=190
  _globals['_WORDCOUNT']._serialized_end=273
# @@protoc_insertion_point(module_scope)
